### ISSUE TITLE
Developing on Windows - CodeKit is Mac-only

### ISSUE THREAD

**Issue by jurchiks** [Veraxus/nouveau#8]
What CodeKit-specific features do you use and how would I go about replacing it with something like Webpack, or even just adding the relevant listeners to PhpStorm (there are LESS/SASS/Bower etc listeners available)? I'm sure somebody else has tried to do this.

**Comment by Veraxus** [comment]
You can use any processing system of your choice as setup is very simple.

`assets/scss` compiles to `assets/css`
`assets/js` compiles to `assets/js`, with the extension changed from `js` to `.min.js`

On Windows your options are fairly limited (at least until bash support is formally added), but I've been told [Prepros](https://prepros.io) is a viable Windows alternative to Codekit (OSX) or Gulp (OSX, Linux).

**Comment by jurchiks** [comment]
Actually, I just used the Node.js sass/scss compiler and the yuicompressor. I really don't understand why some people insist on using bundled software like CodeKit and Prepros, especially since it's not free, but uses free software under the hood.
BTW, Gulp is free and is not OSX/Linux, it's JavaScript and as such, platform-agnostic (it even says so in the GitHub readme). If you were using Gulp, I would have had no problems at all.

**Comment by Veraxus** [comment]
I'm glad you found a solution that worked for you!

> I really don't understand why some people insist on using bundled software like CodeKit and Prepros, especially since it's not free, but uses free software under the hood.

I love open source software, but in many cases, there are paid options that are just plain better. For me, it's a simple calculation: Will the software save me time? If so, how much? What is that time worth at my hourly rate? How much time do I need to save before the software has paid for itself?

CodeKit is $35 - if it saves me even 20 minutes over an alternative like Gulp, it's already paid for itself. And the ability to auto-refresh any number of devices simultaneously paid for itself in the first 30 seconds. I love free software, but sometimes paid software just makes more sense.

**Comment by jurchiks** [comment]
That would be fine... If this was a private project.

**Comment by Veraxus** [comment]
Correction: It's *my* project; in which I've invested years and thousands of hours of work, and have decided to share pro-bono (with documentation) entirely at my sole expense; because I believe it's a vast improvement over the alternatives, and because I believe it will benefit other developers in the WordPress community, which I love.

I am under no obligation whatsoever to support anyone's platform, tools, or workflows other than those I choose, free or not. And despite my background in developing on and for the Windows platform, the tides and the tools have dramatically changed. As far as I'm concerned, if you are using Windows for web development in 2016, you are doing it wrong. And if you aren't willing to buy the tools that ultimately saves you time and money (which includes using a Mac), you are again doing it wrong.

Now, if you would like to contribute configurations for other tools or workflows (e.g. Gulp, Node.js, et al.) I am happy to include those for others who also prefer those tools. But my time is limited and valuable, so I will continue to focus *my* time on the tools, techniques, and architecture that *I* prefer and endorse. That means Mac, PhpStorm, CodeKit, SequelPro, et al.

See, the great thing about open source software is this: if **you** want it to do something it doesn't already do, **you** can contribute that. And when others contribute, everyone wins.

**Comment by Veraxus** [comment]
For posterity, Gulp support was added in 0.11.4. 

To use:

1. Switch to the NOUVEAU theme directory.
2. Type `npm install` to install dependencies.
3. Type `npm start` to watch and compile scss and js automatically.
