### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by thegrid22593** [Veraxus/nouveau#9]
I am getting the following error.

Fatal error: Using $this when not in object context in /nfs/c04/h07/mnt/164448/domains/remote.gsandersongraphics.com/html/wozencraftinsurance.dev/wp-content/themes/wozencraft/nv/NV.php on line 189

`$base_dir = $this->path->lib;`

The files work fine on the local MAMP serve with no issues. All I did was upload all the files to the live server via FTP and upload the database to the new server and I am getting the fatal error above when trying to load the index page.

Not sure what the issue is here. I noticed $this is new in the latest update to Nouveau. If we can't get a fix I will just roll back to a previous version.

Thanks in advance!

**Comment by Veraxus** [comment]
I'm guessing your server is running php 5.3 or earlier and your mamp is on 5.4+

This is happening within the autolader since calling $this from within an anonymous function requires 5.4 or newer. Although the documentation needs updating, going forward NOUVEAU will support only the earliest non-EOL php version of newer.

Fix Options:

1. Upgrade php to a newer version.
2. Move the anonymous function in `spl_autoload_register()` to a named method of Plugin and call that from `spl_autoload_register()` instead.
3. Assign $this to another proxy variable within `Plugin::autoload()` and set base dir using the proxy instead $this: `$base_dir = $proxy->path->lib;`

**Comment by thegrid22593** [comment]
Yea… turns out that is the issue and my host won’t be updating anytime soon.

Thanks for the heads up!

Best,

Garrett
